Repository denoland/deno, pull requests merged in 2024-09, with the labels that each got.

#25398 fix(cli): Map error kind to `PermissionDenied` when symlinking fails due to permissions
  cli/util/fs.rs
Labels: backport:1.46

#25387 fix(ext/node): close upgraded socket when the underlying http connection is closed
  ext/node/ops/http.rs
  tests/unit_node/http_test.ts
Labels: ci-draft

#25443 chore(tests): reduce the use of `--unstable` flag in test util
  tests/unit/test_util.ts
Labels: ci-draft

#25481 fix(ext/node): delay accept() call 2 ticks in net.Server#listen
  ext/node/polyfills/internal_binding/tcp_wrap.ts
  tests/unit_node/net_test.ts
Labels: ci-draft

#25547 bench: fix CI
  cli/bench/http.rs
Labels: ci-bench

#25550 fix(ext/node): avoid showing `UNKNOWN` error from TCP handle
  ext/node/polyfills/internal_binding/stream_wrap.ts
  tests/unit_node/tls_test.ts
Labels: ci-draft

#25699 fix(ext/node): don't throw error for unsupported signal binding on windows
  ext/node/polyfills/process.ts
  tests/unit_node/process_test.ts
Labels: ci-draft

#25736 fix(coverage): ignore urls from doc testing
  cli/tools/coverage/mod.rs
  tests/specs/coverage/filter_doc_testing_urls/__test__.jsonc
  tests/specs/coverage/filter_doc_testing_urls/coverage_success.out
  tests/specs/coverage/filter_doc_testing_urls/source.ts
  tests/specs/coverage/filter_doc_testing_urls/test.ts
  tests/specs/coverage/filter_doc_testing_urls/test_coverage.out
Labels: ci-draft
