Repository denoland/deno, pull requests merged in 2024-08, with the labels that each got.

#24402 feat: async context
  ext/node/lib.rs
  ext/node/polyfills/_next_tick.ts
  ext/node/polyfills/async_hooks.ts
  ext/web/02_timers.js
  runtime/js/01_async_context.js
  runtime/ops/runtime.rs
  runtime/shared.rs
  tests/unit_node/async_hooks_test.ts
Labels: node compat, node API polyfill

#24596 feat: vm rewrite
  ext/node/lib.rs
  ext/node/ops/mod.rs
  ext/node/ops/vm.rs
  ext/node/polyfills/assert.ts
  ext/node/polyfills/vm.js
  ext/node/polyfills/vm.ts
  runtime/snapshot.rs
  tests/node_compat/config.jsonc
  tests/node_compat/runner/TODO.md
  tests/node_compat/test.ts
  tests/node_compat/test/common/index.js
  tests/node_compat/test/parallel/test-vm-access-process-env.js
  tests/node_compat/test/parallel/test-vm-attributes-property-not-on-sandbox.js
  tests/node_compat/test/parallel/test-vm-codegen.js
  tests/node_compat/test/parallel/test-vm-context-async-script.js
  tests/node_compat/test/parallel/test-vm-context-property-forwarding.js
  tests/node_compat/test/parallel/test-vm-create-and-run-in-context.js
  tests/node_compat/test/parallel/test-vm-create-context-accessors.js
  tests/node_compat/test/parallel/test-vm-create-context-arg.js
  tests/node_compat/test/parallel/test-vm-create-context-circular-reference.js
  tests/node_compat/test/parallel/test-vm-createcacheddata.js
  tests/node_compat/test/parallel/test-vm-cross-context.js
  tests/node_compat/test/parallel/test-vm-data-property-writable.js
  tests/node_compat/test/parallel/test-vm-deleting-property.js
  tests/node_compat/test/parallel/test-vm-function-declaration.js
  tests/node_compat/test/parallel/test-vm-function-redefinition.js
  tests/node_compat/test/parallel/test-vm-getters.js
  tests/node_compat/test/parallel/test-vm-global-assignment.js
  tests/node_compat/test/parallel/test-vm-global-define-property.js
  tests/node_compat/test/parallel/test-vm-global-identity.js
  tests/node_compat/test/parallel/test-vm-global-setter.js
  tests/node_compat/test/parallel/test-vm-harmony-symbols.js
  tests/node_compat/test/parallel/test-vm-indexed-properties.js
  tests/node_compat/test/parallel/test-vm-inherited_properties.js
  tests/node_compat/test/parallel/test-vm-is-context.js
  tests/node_compat/test/parallel/test-vm-low-stack-space.js
  tests/node_compat/test/parallel/test-vm-new-script-new-context.js
  tests/node_compat/test/parallel/test-vm-not-strict.js
  tests/node_compat/test/parallel/test-vm-options-validation.js
  tests/node_compat/test/parallel/test-vm-parse-abort-on-uncaught-exception.js
  tests/node_compat/test/parallel/test-vm-preserves-property.js
  tests/node_compat/test/parallel/test-vm-property-not-on-sandbox.js
  tests/node_compat/test/parallel/test-vm-proxies.js
  tests/node_compat/test/parallel/test-vm-proxy-failure-CP.js
  tests/node_compat/test/parallel/test-vm-script-throw-in-tostring.js
  tests/node_compat/test/parallel/test-vm-set-property-proxy.js
  tests/node_compat/test/parallel/test-vm-set-proto-null-on-globalthis.js
  tests/node_compat/test/parallel/test-vm-source-map-url.js
  tests/node_compat/test/parallel/test-vm-strict-mode.js
  tests/node_compat/test/parallel/test-vm-symbols.js
  tests/node_compat/test/parallel/test-vm-timeout-escape-promise-2.js
  tests/node_compat/test/parallel/test-vm-timeout-escape-promise.js
  tests/node_compat/test/parallel/test-vm-timeout.js
  tests/unit_node/vm_test.ts
Labels: node compat, node API polyfill, ci-draft, node:vm

#25229 fix(ext/fetch): percent decode userinfo when parsing proxies
  ext/fetch/proxy.rs
Labels: backport:1.46

#25221 fix(permissions): disallow launching subprocess with LD_PRELOAD env var without full run permissions
  runtime/ops/process.rs
  tests/specs/run/ld_preload/__test__.jsonc
  tests/specs/run/ld_preload/env_arg.out
  tests/specs/run/ld_preload/env_arg.ts
  tests/specs/run/ld_preload/set_with_allow_env.out
  tests/specs/run/ld_preload/set_with_allow_env.ts
Labels: backport:1.46

#25214 feat: remove `--lock-write` flag
  cli/args/flags.rs
  cli/args/lockfile.rs
  cli/tools/installer.rs
  tests/integration/npm_tests.rs
  tests/specs/lockfile/no_declaration_files/__test__.jsonc
  tests/specs/lockfile/no_declaration_files/main.cache.out
  tests/testdata/run/lock_write_fetch/file_exists.ts
  tests/testdata/run/lock_write_fetch/main.ts
Labels: pr:2.0

#25200 fix(publish): ensure provenance is spec compliant
  cli/tools/registry/mod.rs
  cli/tools/registry/provenance.rs
Labels: backport:1.46
