Repository denoland/deno, pull requests merged in 2024-10, with the labels that each got.

#26264 fix(ext/node): fix dns.lookup result ordering
  ext/node/polyfills/http.ts
  ext/node/polyfills/internal/dns/utils.ts
  ext/node/polyfills/internal_binding/cares_wrap.ts
  ext/node/polyfills/net.ts
  tests/unit_node/http_test.ts
  tests/unit_node/tls_test.ts
Labels: ci-draft

#26325 Reland feat(lsp): deno/didRefreshDenoConfigurationTree notifications
  cli/bench/lsp.rs
  cli/bench/lsp_bench_standalone.rs
  cli/lsp/capabilities.rs
  cli/lsp/client.rs
  cli/lsp/config.rs
  cli/lsp/language_server.rs
  cli/lsp/lsp_custom.rs
  tests/integration/lsp_tests.rs
Labels: ci-bench

#26366 ci: use self-hosted mac arm runner
  .github/workflows/ci.generate.ts
  .github/workflows/ci.yml
Labels: ci-full

#26389 feat: support node-api in denort
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/build.rs
  cli/main.rs
  cli/napi/README.md
  cli/napi/mod.rs
  ext/napi/Cargo.toml
  ext/napi/README.md
  ext/napi/build.rs
  ext/napi/generated_symbol_exports_list_linux.def
  ext/napi/generated_symbol_exports_list_macos.def
  ext/napi/generated_symbol_exports_list_windows.def
  ext/napi/js_native_api.rs
  ext/napi/lib.rs
  ext/napi/node_api.rs
  ext/napi/sym/Cargo.toml
  ext/napi/sym/README.md
  ext/napi/sym/lib.rs
  ext/napi/sym/symbol_exports.json
  ext/napi/util.rs
  ext/napi/uv.rs
  tools/napi/generate_symbols_lists.js
Labels: ci-draft

#26579 fix: report exceptions from nextTick
  ext/node/polyfills/_next_tick.ts
  tests/integration/node_unit_tests.rs
  tests/node_compat/config.jsonc
  tests/node_compat/runner/TODO.md
  tests/node_compat/test/parallel/test-child-process-ipc-next-tick.js
  tests/specs/node/next_tick_uncaught_exception/__test__.jsonc
  tests/specs/node/next_tick_uncaught_exception/main.out
  tests/specs/node/next_tick_uncaught_exception/main.ts
Labels: ci-draft
